### ISSUE TITLE
ModuleNotFoundError: No module named 'pytgcalls.types'

### ISSUE THREAD

**Issue by talhazan** [subinps/VCPlayerBot#1]
Hi There, just trying out your application, getting a python exception 

Python 3.7.3 (default, Jan 22 2021, 20:04:44) 

> 
Successfully installed Pyrogram-1.2.9 aiohttp-3.7.4.post0 anyio-3.3.1 async-lru-1.0.2 async-timeout-3.0.1 attrs-21.2.0 bidict-0.21.3 charset-normalizer-2.0.4 ffmpeg-python-0.2.0 future-0.18.2 h11-0.12.0 httpcore-0.13.6 httpx-0.19.0 multidict-5.1.0 psutil-5.8.0 py-tgcalls-0.6.0 pyaes-1.6.1 pysocks-1.7.1 python-engineio-4.2.1 python-socketio-5.4.0 rfc3986-1.5.0 sniffio-1.2.0 tgcrypto-1.2.2 typing-extensions-3.10.0.2 yarl-1.6.3 youtube-search-2.1.0 youtube-search-python-1.4.7

```
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    from utils import start_stream
  File "/home/aurax/VCPlayerBot/utils.py", line 16, in <module>
    from pytgcalls.types.input_stream import InputAudioStream, InputVideoStream, AudioParameters, VideoParameters
ModuleNotFoundError: No module named 'pytgcalls.types'

```

**Comment by talhazan** [comment]
Solved it with pip3 install git+https://github.com/pytgcalls/pytgcalls -U

**Comment by talhazan** [comment]
SUBIN can you please share a 'working example' of app.json ?

Not clear about where to put hash and app id etc.

aurax@aurax:~/VCPlayerBot$ python3 main.py 
[11-Sep-21 01:14:43 - WARNING] - logger - YouTube Stream is set as STARTUP STREAM
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    from utils import start_stream
  File "/home/aurax/VCPlayerBot/utils.py", line 24, in <module>
    from user import group_call, USER
  File "/home/aurax/VCPlayerBot/user.py", line 17, in <module>
    from config import Config
  File "/home/aurax/VCPlayerBot/config.py", line 42, in <module>
    class Config:
  File "/home/aurax/VCPlayerBot/config.py", line 46, in Config
    API_ID = int(os.environ.get("API_ID", ''))
ValueError: invalid literal for int() with base 10: ''

**Comment by bryanseth** [comment]
2021-09-11T03:58:59.829151+00:00 app[worker.1]: pyrogram.errors.exceptions.bad_request_400.ChannelInvalid: [400 CHANNEL_INVALID]: The channel parameter is invalid (caused by "channels.GetChannels")
2021-09-11T03:59:00.136253+00:00 heroku[worker.1]: Process exited with status 1
2021-09-11T03:59:00.229859+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by subinps** [comment]
https://youtu.be/mnWgZMrNe_0
