### ISSUE TITLE
pyrogram.errors.exceptions.not_acceptable_406.AuthKeyDuplicated: [406 AUTH_KEY_DUPLICATED]: The same authorization key (session file) was used in more than one place simultaneously. You must delete your session file and log in again with your phone number or bot token (caused by "InvokeWithLayer")

### ISSUE THREAD

**Issue by talhazan** [subinps/VCPlayerBot#3]
`Starting Bot....
[11-Sep-21 22:06:57 - WARNING] - logger - YouTube Stream is set as STARTUP STREAM
Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>;
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

Traceback (most recent call last):
  File "/VCPlayerBot/main.py", line 43, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/VCPlayerBot/main.py", line 34, in main
    await group_call.start()
  File "/usr/local/lib/python3.9/dist-packages/pytgcalls/methods/utilities/start.py", line 14, in start
    await self._init_mtproto()
  File "/usr/local/lib/python3.9/dist-packages/pytgcalls/methods/utilities/mtproto_handler.py", line 7, in _init_mtproto
    await self._app.start()
  File "/usr/local/lib/python3.9/dist-packages/pytgcalls/mtproto/mtproto_client.py", line 136, in start
    await self._bind_client.start()
  File "/usr/local/lib/python3.9/dist-packages/pytgcalls/mtproto/pyrogram_client.py", line 316, in start
    await self._app.start()
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/utilities/start.py", line 53, in start
    is_authorized = await self.connect()
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/methods/auth/connect.py", line 46, in connect
    await self.session.start()
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/session/session.py", line 172, in start
    raise e
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/session/session.py", line 147, in start
    await self._send(
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/session/session.py", line 396, in _send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.9/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.not_acceptable_406.AuthKeyDuplicated: [406 AUTH_KEY_DUPLICATED]: The same authorization key (session file) was used in more than one place simultaneously. You must delete your session file and log in again with your phone number or bot token (caused by "InvokeWithLayer")`

any idea?

**Comment by subinps** [comment]
Change your session string
