### ISSUE TITLE
Bot Not Starting ...?

### ISSUE THREAD

**Issue by KavinduShehan2006** [subinps/VCPlayerBot#79]
2021-12-11T02:54:00.996805+00:00 app[worker.1]: Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.9/site-packages (from aiohttp->py-tgcalls->-r requirements.txt (line 2)) (21.2.0)
2021-12-11T02:54:00.997551+00:00 app[worker.1]: Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.9/site-packages (from aiohttp->py-tgcalls->-r requirements.txt (line 2)) (4.0.1)
2021-12-11T02:54:00.998160+00:00 app[worker.1]: Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.9/site-packages (from aiohttp->py-tgcalls->-r requirements.txt (line 2)) (1.7.2)
2021-12-11T02:54:01.027853+00:00 app[worker.1]: Requirement already satisfied: typing-extensions>=3.6.5 in /usr/local/lib/python3.9/site-packages (from async-timeout<5.0,>=4.0.0a3->aiohttp->py-tgcalls->-r requirements.txt (line 2)) (4.0.1)
2021-12-11T02:54:01.137173+00:00 app[worker.1]: Requirement already satisfied: tzdata in /usr/local/lib/python3.9/site-packages (from pytz-deprecation-shim->tzlocal!=3.*,>=2.0->apscheduler->-r requirements.txt (line 14)) (2021.5)
2021-12-11T02:54:01.245031+00:00 app[worker.1]: WARNING: Ignoring invalid distribution -wh-pip (/usr/local/lib/python3.9/site-packages)
2021-12-11T02:54:01.401529+00:00 app[worker.1]: WARNING: Ignoring invalid distribution -wh-pip (/usr/local/lib/python3.9/site-packages)
2021-12-11T02:54:01.417452+00:00 app[worker.1]: WARNING: Ignoring invalid distribution -wh-pip (/usr/local/lib/python3.9/site-packages)
2021-12-11T02:54:02.807533+00:00 app[worker.1]: Starting Bot....
2021-12-11T02:54:03.352578+00:00 app[worker.1]: [11-Dec-21 02:54:03 - INFO] - utils.logger - Reply Message Found, Enabled PM MSG
2021-12-11T02:54:37.087380+00:00 app[worker.1]: Traceback (most recent call last):
2021-12-11T02:54:37.087558+00:00 app[worker.1]:   File "/VCPlayerBot/main.py", line 15, in <module>
2021-12-11T02:54:37.087805+00:00 app[worker.1]:     from utils import (
2021-12-11T02:54:37.087839+00:00 app[worker.1]:   File "/VCPlayerBot/utils/__init__.py", line 4, in <module>
2021-12-11T02:54:37.087938+00:00 app[worker.1]:     from .utils import *
2021-12-11T02:54:37.087952+00:00 app[worker.1]:   File "/VCPlayerBot/utils/utils.py", line 101, in <module>
2021-12-11T02:54:37.088111+00:00 app[worker.1]:     scheduler.start()
2021-12-11T02:54:37.088135+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/asyncio.py", line 45, in start
2021-12-11T02:54:37.088400+00:00 app[worker.1]:     super(AsyncIOScheduler, self).start(paused)
2021-12-11T02:54:37.088417+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 163, in start
2021-12-11T02:54:37.088643+00:00 app[worker.1]:     store.start(self, alias)
2021-12-11T02:54:37.088659+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/apscheduler/jobstores/mongodb.py", line 57, in start
2021-12-11T02:54:37.088803+00:00 app[worker.1]:     self.collection.create_index('next_run_time', sparse=True)
2021-12-11T02:54:37.088819+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 2101, in create_index
2021-12-11T02:54:37.089851+00:00 app[worker.1]:     return self.__create_indexes([index], session, **cmd_options)[0]
2021-12-11T02:54:37.089873+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 1961, in __create_indexes
2021-12-11T02:54:37.090936+00:00 app[worker.1]:     with self._socket_for_writes(session) as sock_info:
2021-12-11T02:54:37.090973+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 198, in _socket_for_writes
2021-12-11T02:54:37.091167+00:00 app[worker.1]:     return self.__database.client._socket_for_writes(session)
2021-12-11T02:54:37.091193+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1356, in _socket_for_writes
2021-12-11T02:54:37.092844+00:00 app[worker.1]:     server = self._select_server(writable_server_selector, session)
2021-12-11T02:54:37.092864+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1346, in _select_server
2021-12-11T02:54:37.093408+00:00 app[worker.1]:     server = topology.select_server(server_selector)
2021-12-11T02:54:37.093425+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 244, in select_server
2021-12-11T02:54:37.093602+00:00 app[worker.1]:     return random.choice(self.select_servers(selector,
2021-12-11T02:54:37.094269+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 202, in select_servers
2021-12-11T02:54:37.094437+00:00 app[worker.1]:     server_descriptions = self._select_servers_loop(
2021-12-11T02:54:37.094456+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
2021-12-11T02:54:37.094617+00:00 app[worker.1]:     raise ServerSelectionTimeoutError(
2021-12-11T02:54:37.094650+00:00 app[worker.1]: pymongo.errors.ServerSelectionTimeoutError: connection closed,connection closed,connection closed, Timeout: 30s, Topology Description: <TopologyDescription id: 61b412cf7d26a5d288315238, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.h6bga.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>, <ServerDescription ('cluster0-shard-00-01.h6bga.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>, <ServerDescription ('cluster0-shard-00-02.h6bga.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>]>
2021-12-11T02:54:38.088708+00:00 heroku[worker.1]: Process exited with status 1
2021-12-11T02:54:38.155671+00:00 heroku[worker.1]: State changed from up to crashed
2021-12-11T02:54:38.199796+00:00 heroku[worker.1]: State changed from crashed to starting
2021-12-11T02:55:00.484683+00:00 heroku[worker.1]: Starting process with command `/bin/bash /start.sh`
2021-12-11T02:55:01.266003+00:00 heroku[worker.1]: State changed from starting to up
2021-12-11T02:55:01.859440+00:00 app[worker.1]: Cloning Repo....
2021-12-11T02:55:01.875622+00:00 app[worker.1]: Cloning main branch....
2021-12-11T02:55:01.893503+00:00 app[worker.1]: Cloning into '/VCPlayerBot'...
2021-12-11T02:55:02.851287+00:00 app[worker.1]: WARNING: Ignoring invalid distribution -wh-pip (/usr/local/lib/python3.9/site-packages)
2021-12-11T02:55:02.878997+00:00 app[worker.1]: WARNING: Ignoring invalid distribution -wh-pip (/usr/local/lib/python3.9/site-packages)
2021-12-11T02:55:02.890325+00:00 app[worker.1]: Collecting git+https://github.com/pyrogram/pyrogram@master (from -r requirements.txt (line 1))
2021-12-11T02:55:02.891448+00:00 app[worker.1]:   Cloning https://github.com/pyrogram/pyrogram (to revision master) to /tmp/pip-req-build-pbk9y2_m
2021-12-11T02:55:02.900162+00:00 app[worker.1]:   Running command git clone --filter=blob:none -q https://github.com/pyrogram/pyrogram /tmp/pip-req-build-pbk9y2_m
2021-12-11T02:55:04.340308+00:00 app[worker.1]:   Resolved https://github.com/pyrogram/pyrogram to commit bf9e1864141bdab1a4f20393c7d10fcf8c522f63
2021-12-11T02:55:04.341526+00:00 app[worker.1]:   Preparing metadata (setup.py): started
2021-12-11T02:55:04.828985+00:00 app[worker.1]:   Preparing metadata (setup.py): finished with status 'done'
2021-12-11T02:55:04.835404+00:00 app[worker.1]: Requirement already satisfied: py-tgcalls in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (0.8.1)
2021-12-11T02:55:05.174418+00:00 app[worker.1]: Requirement already satisfied: parse-torrent-name in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (1.1.1)
2021-12-11T02:55:05.217257+00:00 app[worker.1]: Requirement already satisfied: tgcrypto in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (1.2.2)
2021-12-11T02:55:05.354037+00:00 app[worker.1]: Requirement already satisfied: yt-dlp in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (2021.12.1)
2021-12-11T02:55:05.432720+00:00 app[worker.1]: Requirement already satisfied: youtube-search-python in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (1.5.3)
2021-12-11T02:55:05.517771+00:00 app[worker.1]: Requirement already satisfied: httpx==0.14.2 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (0.14.2)
2021-12-11T02:55:05.626544+00:00 app[worker.1]: Requirement already satisfied: youtube-search in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (2.1.0)
2021-12-11T02:55:05.648542+00:00 app[worker.1]: Requirement already satisfied: heroku3 in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (5.1.4)
2021-12-11T02:55:05.685049+00:00 app[worker.1]: Requirement already satisfied: pillow in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 10)) (8.4.0)
2021-12-11T02:55:06.769577+00:00 app[worker.1]: Requirement already satisfied: motor in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 11)) (2.5.1)
2021-12-11T02:55:06.843682+00:00 app[worker.1]: Requirement already satisfied: dnspython in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 12)) (2.1.0)
2021-12-11T02:55:06.895853+00:00 app[worker.1]: Requirement already satisfied: pytz in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 13)) (2021.3)
2021-12-11T02:55:07.139618+00:00 app[worker.1]: Requirement already satisfied: apscheduler in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 14)) (3.8.1)
2021-12-11T02:55:07.218896+00:00 app[worker.1]: Requirement already satisfied: python-dotenv in /usr/local/lib/python3.9/site-packages (from -r requirements.txt (line 15)) (0.19.2)
2021-12-11T02:55:07.311422+00:00 app[worker.1]: Requirement already satisfied: sniffio in /usr/local/lib/python3.9/site-packages (from httpx==0.14.2->-r requirements.txt (line 7)) (1.2.0)
2021-12-11T02:55:07.312392+00:00 app[worker.1]: Requirement already satisfied: chardet==3.* in /usr/local/lib/python3.9/site-packages (from httpx==0.14.2->-r requirements.txt (line 7)) (3.0.4)
2021-12-11T02:55:07.313274+00:00 app[worker.1]: Requirement already satisfied: httpcore==0.10.* in /usr/local/lib/python3.9/site-packages (from httpx==0.14.2->-r requirements.txt (line 7)) (0.10.2)
2021-12-11T02:55:07.313630+00:00 app[worker.1]: Requirement already satisfied: certifi in /usr/local/lib/python3.9/site-packages (from httpx==0.14.2->-r requirements.txt (line 7)) (2021.10.8)
2021-12-11T02:55:07.314874+00:00 app[worker.1]: Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /usr/local/lib/python3.9/site-packages (from httpx==0.14.2->-r requirements.txt (line 7)) (1.5.0)
2021-12-11T02:55:07.323051+00:00 app[worker.1]: Requirement already satisfied: h11<0.10,>=0.8 in /usr/local/lib/python3.9/site-packages (from httpcore==0.10.*->httpx==0.14.2->-r requirements.txt (line 7)) (0.9.0)
2021-12-11T02:55:07.331595+00:00 app[worker.1]: Requirement already satisfied: pyaes==1.6.1 in /usr/local/lib/python3.9/site-packages (from Pyrogram==1.2.9->-r requirements.txt (line 1)) (1.6.1)
2021-12-11T02:55:07.333077+00:00 app[worker.1]: Requirement already satisfied: pysocks==1.7.1 in /usr/local/lib/python3.9/site-packages (from Pyrogram==1.2.9->-r requirements.txt (line 1)) (1.7.1)
2021-12-11T02:55:07.341710+00:00 app[worker.1]: Requirement already satisfied: aiohttp in /usr/local/lib/python3.9/site-packages (from py-tgcalls->-r requirements.txt (line 2)) (3.8.1)
2021-12-11T02:55:07.342416+00:00 app[worker.1]: Requirement already satisfied: psutil in /usr/local/lib/python3.9/site-packages (from py-tgcalls->-r requirements.txt (line 2)) (5.8.0)
2021-12-11T02:55:07.355733+00:00 app[worker.1]: Requirement already satisfied: mutagen in /usr/local/lib/python3.9/site-packages (from yt-dlp->-r requirements.txt (line 5)) (1.45.1)
2021-12-11T02:55:07.356105+00:00 app[worker.1]: Requirement already satisfied: pycryptodomex in /usr/local/lib/python3.9/site-packages (from yt-dlp->-r requirements.txt (line 5)) (3.12.0)
2021-12-11T02:55:07.356516+00:00 app[worker.1]: Requirement already satisfied: websockets in /usr/local/lib/python3.9/site-packages (from yt-dlp->-r requirements.txt (line 5)) (10.1)
2021-12-11T02:55:07.372496+00:00 app[worker.1]: Requirement already satisfied: requests in /usr/local/lib/python3.9/site-packages (from youtube-search->-r requirements.txt (line 8)) (2.26.0)
2021-12-11T02:55:07.378628+00:00 app[worker.1]: Requirement already satisfied: python-dateutil>=2.6.0 in /usr/local/lib/python3.9/site-packages (from heroku3->-r requirements.txt (line 9)) (2.8.2)
2021-12-11T02:55:07.384880+00:00 app[worker.1]: Requirement already satisfied: pymongo<4,>=3.12 in /usr/local/lib/python3.9/site-packages (from motor->-r requirements.txt (line 11)) (3.12.3)
2021-12-11T02:55:07.448659+00:00 app[worker.1]: Requirement already satisfied: tzlocal!=3.*,>=2.0 in /usr/local/lib/python3.9/site-packages (from apscheduler->-r requirements.txt (line 14)) (4.1)
2021-12-11T02:55:07.449637+00:00 app[worker.1]: Requirement already satisfied: setuptools>=0.7 in /usr/local/lib/python3.9/site-packages (from apscheduler->-r requirements.txt (line 14)) (57.5.0)
2021-12-11T02:55:07.450766+00:00 app[worker.1]: Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.9/site-packages (from apscheduler->-r requirements.txt (line 14)) (1.16.0)
2021-12-11T02:55:07.550973+00:00 app[worker.1]: Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests->youtube-search->-r requirements.txt (line 8)) (3.3)
2021-12-11T02:55:07.552485+00:00 app[worker.1]: Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/site-packages (from requests->youtube-search->-r requirements.txt (line 8)) (1.26.7)
2021-12-11T02:55:07.554566+00:00 app[worker.1]: Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/site-packages (from requests->youtube-search->-r requirements.txt (line 8)) (2.0.9)
2021-12-11T02:55:07.585240+00:00 app[worker.1]: Requirement already satisfied: pytz-deprecation-shim in /usr/local/lib/python3.9/site-packages (from tzlocal!=3.*,>=2.0->apscheduler->-r requirements.txt (line 14)) (0.1.0.post0)
2021-12-11T02:55:07.606926+00:00 app[worker.1]: Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.9/site-packages (from aiohttp->py-tgcalls->-r requirements.txt (line 2)) (5.2.0)
2021-12-11T02:55:07.607902+00:00 app[worker.1]: Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.9/site-packages (from aiohttp->py-tgcalls->-r requirements.txt (line 2)) (1.7.2)
2021-12-11T02:55:07.608853+00:00 app[worker.1]: Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.9/site-packages (from aiohttp->py-tgcalls->-r requirements.txt (line 2)) (4.0.1)
2021-12-11T02:55:07.609638+00:00 app[worker.1]: Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.9/site-packages (from aiohttp->py-tgcalls->-r requirements.txt (line 2)) (1.2.0)
2021-12-11T02:55:07.610402+00:00 app[worker.1]: Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.9/site-packages (from aiohttp->py-tgcalls->-r requirements.txt (line 2)) (21.2.0)
2021-12-11T02:55:07.611493+00:00 app[worker.1]: Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.9/site-packages (from aiohttp->py-tgcalls->-r requirements.txt (line 2)) (1.2.0)
2021-12-11T02:55:07.650659+00:00 app[worker.1]: Requirement already satisfied: typing-extensions>=3.6.5 in /usr/local/lib/python3.9/site-packages (from async-timeout<5.0,>=4.0.0a3->aiohttp->py-tgcalls->-r requirements.txt (line 2)) (4.0.1)
2021-12-11T02:55:07.758860+00:00 app[worker.1]: Requirement already satisfied: tzdata in /usr/local/lib/python3.9/site-packages (from pytz-deprecation-shim->tzlocal!=3.*,>=2.0->apscheduler->-r requirements.txt (line 14)) (2021.5)
2021-12-11T02:55:07.821809+00:00 app[worker.1]: WARNING: Ignoring invalid distribution -wh-pip (/usr/local/lib/python3.9/site-packages)
2021-12-11T02:55:07.980444+00:00 app[worker.1]: WARNING: Ignoring invalid distribution -wh-pip (/usr/local/lib/python3.9/site-packages)
2021-12-11T02:55:07.981185+00:00 app[worker.1]: WARNING: Ignoring invalid distribution -wh-pip (/usr/local/lib/python3.9/site-packages)
2021-12-11T02:55:08.378270+00:00 app[worker.1]: Starting Bot....
2021-12-11T02:55:08.805388+00:00 app[worker.1]: [11-Dec-21 02:55:08 - INFO] - utils.logger - Reply Message Found, Enabled PM MSG
2021-12-11T02:55:40.882128+00:00 app[worker.1]: Traceback (most recent call last):
2021-12-11T02:55:40.882215+00:00 app[worker.1]:   File "/VCPlayerBot/main.py", line 15, in <module>
2021-12-11T02:55:40.882506+00:00 app[worker.1]:     from utils import (
2021-12-11T02:55:40.882524+00:00 app[worker.1]:   File "/VCPlayerBot/utils/__init__.py", line 4, in <module>
2021-12-11T02:55:40.882672+00:00 app[worker.1]:     from .utils import *
2021-12-11T02:55:40.882688+00:00 app[worker.1]:   File "/VCPlayerBot/utils/utils.py", line 101, in <module>
2021-12-11T02:55:40.882905+00:00 app[worker.1]:     scheduler.start()
2021-12-11T02:55:40.882925+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/asyncio.py", line 45, in start
2021-12-11T02:55:40.883114+00:00 app[worker.1]:     super(AsyncIOScheduler, self).start(paused)
2021-12-11T02:55:40.883140+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 163, in start
2021-12-11T02:55:40.883344+00:00 app[worker.1]:     store.start(self, alias)
2021-12-11T02:55:40.883384+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/apscheduler/jobstores/mongodb.py", line 57, in start
2021-12-11T02:55:40.883561+00:00 app[worker.1]:     self.collection.create_index('next_run_time', sparse=True)
2021-12-11T02:55:40.883579+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 2101, in create_index
2021-12-11T02:55:40.886385+00:00 app[worker.1]:     return self.__create_indexes([index], session, **cmd_options)[0]
2021-12-11T02:55:40.886429+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 1961, in __create_indexes
2021-12-11T02:55:40.888818+00:00 app[worker.1]:     with self._socket_for_writes(session) as sock_info:
2021-12-11T02:55:40.888891+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 198, in _socket_for_writes
2021-12-11T02:55:40.889194+00:00 app[worker.1]:     return self.__database.client._socket_for_writes(session)
2021-12-11T02:55:40.889218+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1356, in _socket_for_writes
2021-12-11T02:55:40.890032+00:00 app[worker.1]:     server = self._select_server(writable_server_selector, session)
2021-12-11T02:55:40.890070+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1346, in _select_server
2021-12-11T02:55:40.890694+00:00 app[worker.1]:     server = topology.select_server(server_selector)
2021-12-11T02:55:40.890714+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 244, in select_server
2021-12-11T02:55:40.890941+00:00 app[worker.1]:     return random.choice(self.select_servers(selector,
2021-12-11T02:55:40.890959+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 202, in select_servers
2021-12-11T02:55:40.891123+00:00 app[worker.1]:     server_descriptions = self._select_servers_loop(
2021-12-11T02:55:40.891140+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
2021-12-11T02:55:40.891314+00:00 app[worker.1]:     raise ServerSelectionTimeoutError(
2021-12-11T02:55:40.891350+00:00 app[worker.1]: pymongo.errors.ServerSelectionTimeoutError: connection closed,connection closed,connection closed, Timeout: 30s, Topology Description: <TopologyDescription id: 61b4130eb52491b4063a01a4, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.h6bga.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>, <ServerDescription ('cluster0-shard-00-01.h6bga.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>, <ServerDescription ('cluster0-shard-00-02.h6bga.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>]>
2021-12-11T02:55:41.993418+00:00 heroku[worker.1]: Process exited with status 1
2021-12-11T02:55:42.052226+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by HaxNik** [comment]
Mongo url sahi dalo

**Comment by vijay991738** [comment]
plese help
bot not work
